version: "3"
services:
  mongodb:
    image: mongo:4.2.9
    container_name: clt_mongo
    restart: always
    volumes:
      - "./db_data/mongo:/data/db"
      - "./db_data/mongodb_dump:/root/dump"
      - "./images:/static/images"
  redis:
    image: redis:6.0-alpine
    container_name: clt_redis
    restart: always
  server:
    image: clt_server:latest
    container_name: clt_server
    restart: always
    environment:
      - HTTP_PORT
      - MONGODB_ADDR
      - REDIS_ADDR
    depends_on:
      - mongodb
      - redis
  nginx:
    image: clt_nginx:latest
    container_name: clt_nginx
    restart: always
    volumes:
      - "./images:/web/static/images"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mongodb
      - redis
      - server
